name: Trigger auto deployment for newapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/newapp-AutoDeployTrigger-ce2bc1df-aead-4e51-9042-4da2e80957b6.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: smallone.azurecr.io
          username: ${{ secrets.NEWAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: smallone.azurecr.io/newapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n newapp -g Docker1 --server smallone.azurecr.io --username  ${{ secrets.NEWAPP_REGISTRY_USERNAME }} --password ${{ secrets.NEWAPP_REGISTRY_PASSWORD }}
            az containerapp update -n newapp -g Docker1 --image smallone.azurecr.io/newapp:${{ github.sha }}
