name: Trigger auto deployment for newcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ rhs/test ]
    paths:
    - '**'
    - '.github/workflows/newcontainerapp-AutoDeployTrigger-a5821618-9b3e-4c7a-960e-29176af90f80.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: smallregistrycotainer.azurecr.io
          username: ${{ secrets.NEWCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: smallregistrycotainer.azurecr.io/first:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n newcontainerapp -g Docker1 --server smallregistrycotainer.azurecr.io --username  ${{ secrets.NEWCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.NEWCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n newcontainerapp -g Docker1 --image smallregistrycotainer.azurecr.io/first:${{ github.sha }}
